# Generated by Django 5.2 on 2025-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
