# Generated by Django 5.1.5 on 2025-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
