# Generated by Django 5.1.5 on 2025-02-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('litre', 'Litre')], default='piece', max_length=20),
        ),
    ]
