# Generated by Django 5.2 on 2025-05-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_theme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
