# Generated by Django 5.1.5 on 2025-03-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_report_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
