# Generated by Django 5.2 on 2025-05-10 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_theme_article_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.theme'),
        ),
    ]
