# Generated by Django 5.2 on 2025-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_af',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ar',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ar_dz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ast',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_az',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_be',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_bg',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_bn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_br',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_bs',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ca',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ckb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_cs',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_cy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_da',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_de',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_dsb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_el',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_en',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_en_au',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_en_gb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_eo',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es_ar',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es_co',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es_mx',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es_ni',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_es_ve',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_et',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_eu',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_fa',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_fi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_fr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_fy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ga',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_gd',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_gl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_he',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_hi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_hr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_hsb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_hu',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_hy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ia',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ig',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ind',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_io',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_is',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_it',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ja',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ka',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_kab',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_kk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_km',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_kn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ko',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ky',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_lb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_lt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_lv',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_mk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ml',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_mn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_mr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ms',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_my',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_nb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ne',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_nl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_nn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_os',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_pa',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_pl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_pt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_pt_br',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ro',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ru',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sq',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sr_latn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sv',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_sw',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ta',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_te',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_tg',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_th',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_tk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_tr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_tt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_udm',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ug',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_uk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_ur',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_uz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_vi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_zh_hans',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n_zh_hant',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_af',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ar',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ar_dz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ast',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_az',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_be',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_bg',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_bn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_br',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_bs',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ca',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ckb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_cs',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_cy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_da',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_de',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_dsb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_el',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_en',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_en_au',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_en_gb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_eo',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es_ar',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es_co',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es_mx',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es_ni',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_es_ve',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_et',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_eu',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_fa',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_fi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_fr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_fy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ga',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_gd',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_gl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_he',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_hi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_hr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_hsb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_hu',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_hy',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ia',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ig',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ind',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_io',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_is',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_it',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ja',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ka',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_kab',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_kk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_km',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_kn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ko',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ky',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_lb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_lt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_lv',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_mk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ml',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_mn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_mr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ms',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_my',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_nb',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ne',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_nl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_nn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_os',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_pa',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_pl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_pt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_pt_br',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ro',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ru',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sl',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sq',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sr_latn',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sv',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_sw',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ta',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_te',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_tg',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_th',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_tk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_tr',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_tt',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_udm',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ug',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_uk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_ur',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_uz',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_vi',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_zh_hans',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_i18n_zh_hant',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
