# Generated by Django 5.1.5 on 2025-02-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rentable',
            field=models.BooleanField(default=False),
        ),
    ]
